# Deploy WAR file to Jetty container
# WAR should be in directory ./target as generated by mvn install

# Application requires import.properties file at ${JETTY_BASE}/order/import.properties

FROM jetty
COPY --chown=jetty:jetty target/order.war ${JETTY_HOME}/webapps/
COPY --chown=jetty:jetty import.properties ${JETTY_BASE}/order/
COPY --chown=jetty:jetty docker-config/ROOT.xml ${JETTY_BASE}/webapps/
COPY --chown=jetty:jetty docker-config/order-web.xml ${JETTY_HOME}/webapps/
